"""Add phase 1 fields

Revision ID: f92f33dbcf80
Revises: 29a1917d9bbf
Create Date: 2025-12-11 06:27:08.155977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f92f33dbcf80'
down_revision: Union[str, None] = None  # First migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop constraints FIRST (only if table exists)
    # Skip this as quote_requests table doesn't exist yet
    # op.drop_constraint('quote_requests_selected_provider_id_fkey', 'quote_requests', type_='foreignkey')
    
    op.create_table('providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quote_email', sa.String(), nullable=True),
    sa.Column('support_email', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('is_slow_responder', sa.Boolean(), nullable=True),
    sa.Column('total_leads_sent', sa.Integer(), nullable=True),
    sa.Column('total_deals_won', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('binding_period_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_category'), 'contracts', ['category'], unique=False)
    op.create_index(op.f('ix_contracts_provider'), 'contracts', ['provider'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quote_request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_annual_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_cheapest', sa.Boolean(), nullable=True),
    sa.Column('is_best_value', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('recommendation_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_category'), 'quotes', ['category'], unique=False)
    op.create_index(op.f('ix_quotes_provider'), 'quotes', ['provider'], unique=False)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('support_ticket_id', sa.String(), nullable=True),
    sa.Column('quote_request_id', sa.String(), nullable=True),
    sa.Column('email_type', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_scaffolded', sa.Boolean(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('provider_contact_reason', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['support_tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_energy_providers_name'), table_name='energy_providers')
    op.drop_table('energy_providers')
    op.drop_index(op.f('ix_energy_contracts_provider'), table_name='energy_contracts')
    op.drop_index(op.f('ix_energy_contracts_status'), table_name='energy_contracts')
    op.drop_index(op.f('ix_energy_contracts_user_id'), table_name='energy_contracts')
    op.drop_table('energy_contracts')
    op.add_column('quote_requests', sa.Column('categories', sa.JSON(), nullable=False))
    op.add_column('quote_requests', sa.Column('user_data', sa.JSON(), nullable=True))
    op.alter_column('quote_requests', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'SENT', 'RESPONSES_RECEIVED', 'COMPLETED', 'CANCELLED', name='quoterequeststatus'),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    
    # MOVED UP: op.drop_constraint(op.f('quote_requests_selected_provider_id_fkey'), 'quote_requests', type_='foreignkey')
    
    op.drop_column('quote_requests', 'request_type')
    op.drop_column('quote_requests', 'selected_at')
    op.drop_column('quote_requests', 'user_context')
    op.drop_column('quote_requests', 'selected_provider_id')
    op.drop_column('quote_requests', 'providers')
    op.add_column('users', sa.Column('agent_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('forward_marketing_emails', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('forward_essential_emails', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_azure_id'), table_name='users')
    op.drop_constraint('users_auth0_user_id_key', 'users', type_='unique')
    op.drop_constraint('users_azure_id_key', 'users', type_='unique')
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=True)
    op.create_index(op.f('ix_users_agent_email'), 'users', ['agent_email'], unique=True)
    op.drop_column('users', 'azure_id')
    op.drop_column('users', 'fuldmagt_signed_at')
    op.drop_column('users', 'current_providers')
    op.drop_column('users', 'criipto_signatory_id')
    op.drop_column('users', 'eloverblik_authorized_at')
    op.drop_column('users', 'energy_area')
    op.drop_column('users', 'fuldmagt_signed')
    op.drop_column('users', 'criipto_signature_order_id')
    op.drop_column('users', 'mitid_subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mitid_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('criipto_signature_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fuldmagt_signed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('energy_area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('eloverblik_authorized_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('criipto_signatory_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_providers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fuldmagt_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('azure_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_agent_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=False)
    op.create_unique_constraint('users_azure_id_key', 'users', ['azure_id'])
    op.create_unique_constraint('users_auth0_user_id_key', 'users', ['auth0_user_id'])
    op.create_index(op.f('ix_users_azure_id'), 'users', ['azure_id'], unique=False)
    op.drop_column('users', 'forward_essential_emails')
    op.drop_column('users', 'forward_marketing_emails')
    op.drop_column('users', 'agent_email')
    op.add_column('quote_requests', sa.Column('providers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('quote_requests', sa.Column('selected_provider_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quote_requests', sa.Column('user_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quote_requests', sa.Column('selected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('quote_requests', sa.Column('request_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('quote_requests_selected_provider_id_fkey', 'quote_requests', 'energy_providers', ['selected_provider_id'], ['id'])
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.alter_column('quote_requests', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DRAFT', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'SENT', 'RESPONSES_RECEIVED', 'COMPLETED', 'CANCELLED', name='quoterequeststatus'),
               nullable=False)
    op.drop_column('quote_requests', 'user_data')
    op.drop_column('quote_requests', 'categories')
    op.create_table('energy_contracts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metering_point_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('energy_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pricing_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fixed_price_dkk_per_kwh', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('subscription_fee_dkk_per_month', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('transport_tariff_dkk_per_kwh', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('binding_period_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notice_period_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_document_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['metering_point_id'], ['metering_points.id'], name='energy_contracts_metering_point_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='energy_contracts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='energy_contracts_pkey')
    )
    op.create_index('ix_energy_contracts_user_id', 'energy_contracts', ['user_id'], unique=False)
    op.create_index('ix_energy_contracts_status', 'energy_contracts', ['status'], unique=False)
    op.create_index('ix_energy_contracts_provider', 'energy_contracts', ['provider'], unique=False)
    op.create_table('energy_providers',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accepts_quote_requests', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='energy_providers_pkey')
    )
    op.create_index('ix_energy_providers_name', 'energy_providers', ['name'], unique=True)
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_provider'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_category'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_provider'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_category'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
